import { HolidayItem, StateInfo } from "./types";

export const INDIAN_STATES: StateInfo[] = [
  { code: "KA", name: "Karnataka", slug: "karnataka", capital: "Bengaluru" },
  { code: "MH", name: "Maharashtra", slug: "maharashtra", capital: "Mumbai" },
  { code: "DL", name: "Delhi (NCR)", slug: "delhi", capital: "New Delhi" },
  { code: "TN", name: "Tamil Nadu", slug: "tamil-nadu", capital: "Chennai" },
  { code: "GJ", name: "Gujarat", slug: "gujarat", capital: "Gandhinagar" },
  { code: "TS", name: "Telangana", slug: "telangana", capital: "Hyderabad" },
  { code: "WB", name: "West Bengal", slug: "west-bengal", capital: "Kolkata" },
  { code: "KL", name: "Kerala", slug: "kerala", capital: "Thiruvananthapuram" },
  { code: "AP", name: "Andhra Pradesh", slug: "andhra-pradesh", capital: "Amaravati" },
  { code: "RJ", name: "Rajasthan", slug: "rajasthan", capital: "Jaipur" },
  { code: "UP", name: "Uttar Pradesh", slug: "uttar-pradesh", capital: "Lucknow" },
  { code: "PB", name: "Punjab", slug: "punjab", capital: "Chandigarh" },
  { code: "MP", name: "Madhya Pradesh", slug: "madhya-pradesh", capital: "Bhopal" },
];

export const HOLIDAYS_DATA: HolidayItem[] = [
  // ---------------------------------------------------------------------------
  // 2026 HOLIDAYS
  // ---------------------------------------------------------------------------
  {
    id: "h2026-01",
    date: "2026-01-01",
    year: 2026,
    month: 1,
    dayName: "Thursday",
    title: "New Year's Day",
    category: "festival",
    categoryName: "Festival / Public",
    states: ["all"],
    longWeekendEligible: true,
    description: "First day of the Gregorian New Year.",
  },
  {
    id: "h2026-02",
    date: "2026-01-14",
    year: 2026,
    month: 1,
    dayName: "Wednesday",
    title: "Makar Sankranti / Pongal",
    category: "festival",
    categoryName: "Festival",
    states: ["karnataka", "maharashtra", "tamil-nadu", "gujarat", "andhra-pradesh", "telangana"],
    description: "Harvest festival celebrated across southern and western India.",
  },
  {
    id: "h2026-03",
    date: "2026-01-15",
    year: 2026,
    month: 1,
    dayName: "Thursday",
    title: "Thiruvalluvar Day / Uttarayan",
    category: "state",
    categoryName: "State Holiday",
    states: ["tamil-nadu", "gujarat"],
  },
  {
    id: "h2026-04",
    date: "2026-01-26",
    year: 2026,
    month: 1,
    dayName: "Monday",
    title: "Republic Day",
    category: "national",
    categoryName: "National Holiday",
    states: ["all"],
    longWeekendEligible: true,
    description: "Commemorates the adoption of the Constitution of India. Mandatory National Holiday.",
  },
  {
    id: "h2026-05",
    date: "2026-02-15",
    year: 2026,
    month: 2,
    dayName: "Sunday",
    title: "Maha Shivratri",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
    description: "Major Hindu festival in honor of Lord Shiva.",
  },
  {
    id: "h2026-06",
    date: "2026-03-03",
    year: 2026,
    month: 3,
    dayName: "Tuesday",
    title: "Holi",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
    longWeekendEligible: true,
    description: "Festival of colors celebrated nationwide.",
  },
  {
    id: "h2026-07",
    date: "2026-03-19",
    year: 2026,
    month: 3,
    dayName: "Thursday",
    title: "Ugadi / Gudi Padwa",
    category: "festival",
    categoryName: "State Festival",
    states: ["karnataka", "maharashtra", "telangana", "andhra-pradesh"],
    longWeekendEligible: true,
    description: "New Year's Day for Deccan states.",
  },
  {
    id: "h2026-08",
    date: "2026-03-21",
    year: 2026,
    month: 3,
    dayName: "Saturday",
    title: "Eid al-Fitr (Ramzan Id)",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
    description: "Islamic festival marking the end of Ramadan.",
  },
  {
    id: "h2026-09",
    date: "2026-04-03",
    year: 2026,
    month: 4,
    dayName: "Friday",
    title: "Good Friday",
    category: "bank",
    categoryName: "Bank / Public",
    states: ["all"],
    longWeekendEligible: true,
    description: "Christian holiday commemorating the passion of Jesus Christ.",
  },
  {
    id: "h2026-10",
    date: "2026-04-14",
    year: 2026,
    month: 4,
    dayName: "Tuesday",
    title: "Dr. B.R. Ambedkar Jayanti / Tamil New Year",
    category: "government",
    categoryName: "Government",
    states: ["all"],
    longWeekendEligible: true,
  },
  {
    id: "h2026-11",
    date: "2026-05-01",
    year: 2026,
    month: 5,
    dayName: "Friday",
    title: "May Day / Maharashtra Day",
    category: "state",
    categoryName: "State / Public",
    states: ["maharashtra", "karnataka", "tamil-nadu", "kerala", "west-bengal", "telangana", "gujarat"],
    longWeekendEligible: true,
    description: "International Workers' Day and Maharashtra Formation Day.",
  },
  {
    id: "h2026-12",
    date: "2026-05-27",
    year: 2026,
    month: 5,
    dayName: "Wednesday",
    title: "Bakrid / Eid al-Adha",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
  },
  {
    id: "h2026-13",
    date: "2026-08-15",
    year: 2026,
    month: 8,
    dayName: "Saturday",
    title: "Independence Day",
    category: "national",
    categoryName: "National Holiday",
    states: ["all"],
    description: "79th Independence Day of India. Mandatory National Holiday.",
  },
  {
    id: "h2026-14",
    date: "2026-08-26",
    year: 2026,
    month: 8,
    dayName: "Wednesday",
    title: "Onam (Thiruvonam)",
    category: "state",
    categoryName: "State Festival",
    states: ["kerala"],
  },
  {
    id: "h2026-15",
    date: "2026-09-14",
    year: 2026,
    month: 9,
    dayName: "Monday",
    title: "Ganesh Chaturthi",
    category: "festival",
    categoryName: "Festival",
    states: ["maharashtra", "karnataka", "gujarat", "telangana", "andhra-pradesh"],
    longWeekendEligible: true,
    description: "Grand celebration of Lord Ganesha.",
  },
  {
    id: "h2026-16",
    date: "2026-10-02",
    year: 2026,
    month: 10,
    dayName: "Friday",
    title: "Mahatma Gandhi Jayanti",
    category: "national",
    categoryName: "National Holiday",
    states: ["all"],
    longWeekendEligible: true,
    description: "Birth anniversary of Mahatma Gandhi. Mandatory National Holiday.",
  },
  {
    id: "h2026-17",
    date: "2026-10-20",
    year: 2026,
    month: 10,
    dayName: "Tuesday",
    title: "Maha Navami / Ayudha Puja",
    category: "festival",
    categoryName: "Festival",
    states: ["karnataka", "tamil-nadu", "west-bengal", "kerala"],
  },
  {
    id: "h2026-18",
    date: "2026-10-21",
    year: 2026,
    month: 10,
    dayName: "Wednesday",
    title: "Dussehra (Vijayadashami)",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
    description: "Victory of good over evil. Major nationwide public holiday.",
  },
  {
    id: "h2026-19",
    date: "2026-11-01",
    year: 2026,
    month: 11,
    dayName: "Sunday",
    title: "Kannada Rajyotsava",
    category: "state",
    categoryName: "State Formation Day",
    states: ["karnataka"],
    description: "Karnataka State Formation Day.",
  },
  {
    id: "h2026-20",
    date: "2026-11-08",
    year: 2026,
    month: 11,
    dayName: "Sunday",
    title: "Deepavali (Diwali)",
    category: "festival",
    categoryName: "Festival",
    states: ["all"],
    description: "Festival of Lights. Major national festival.",
  },
  {
    id: "h2026-21",
    date: "2026-12-25",
    year: 2026,
    month: 12,
    dayName: "Friday",
    title: "Christmas",
    category: "festival",
    categoryName: "Festival / Public",
    states: ["all"],
    longWeekendEligible: true,
    description: "Celebration of the birth of Jesus Christ.",
  },

  // ---------------------------------------------------------------------------
  // 2027 HOLIDAYS (Key National & Festival dates)
  // ---------------------------------------------------------------------------
  { id: "h2027-01", date: "2027-01-01", year: 2027, month: 1, dayName: "Friday", title: "New Year's Day", category: "festival", categoryName: "Festival", states: ["all"], longWeekendEligible: true },
  { id: "h2027-02", date: "2027-01-26", year: 2027, month: 1, dayName: "Tuesday", title: "Republic Day", category: "national", categoryName: "National Holiday", states: ["all"], longWeekendEligible: true },
  { id: "h2027-03", date: "2027-03-22", year: 2027, month: 3, dayName: "Monday", title: "Holi", category: "festival", categoryName: "Festival", states: ["all"], longWeekendEligible: true },
  { id: "h2027-04", date: "2027-03-26", year: 2027, month: 3, dayName: "Friday", title: "Good Friday", category: "bank", categoryName: "Bank / Public", states: ["all"], longWeekendEligible: true },
  { id: "h2027-05", date: "2027-08-15", year: 2027, month: 8, dayName: "Sunday", title: "Independence Day", category: "national", categoryName: "National Holiday", states: ["all"] },
  { id: "h2027-06", date: "2027-10-02", year: 2027, month: 10, dayName: "Saturday", title: "Mahatma Gandhi Jayanti", category: "national", categoryName: "National Holiday", states: ["all"] },
  { id: "h2027-07", date: "2027-10-29", year: 2027, month: 10, dayName: "Friday", title: "Diwali (Deepavali)", category: "festival", categoryName: "Festival", states: ["all"], longWeekendEligible: true },
  { id: "h2027-08", date: "2027-12-25", year: 2027, month: 12, dayName: "Saturday", title: "Christmas", category: "festival", categoryName: "Festival", states: ["all"] },
];

export function getHolidaysByYear(year: number, state: string = "all"): HolidayItem[] {
  return HOLIDAYS_DATA.filter((h) => {
    const matchesYear = h.year === year;
    const matchesState = state === "all" || h.states.includes("all") || h.states.includes(state);
    return matchesYear && matchesState;
  });
}

export function getStateHolidays(stateSlug: string, year: number = 2026): HolidayItem[] {
  return HOLIDAYS_DATA.filter((h) => {
    const matchesYear = h.year === year;
    const matchesState = h.states.includes("all") || h.states.includes(stateSlug);
    return matchesYear && matchesState;
  });
}

export function getStateBySlug(slug: string): StateInfo | undefined {
  return INDIAN_STATES.find((s) => s.slug === slug);
}
